name: Test

on:
  push:

jobs:
  test:
    name: Test
    permissions:
      contents: read
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: test
      shell: bash
      run:
        echo "::add-matcher::$(pwd)/test.json"
        perl -e 'eval { sub foo($$) {return 1; }; foo(); }'
